name: agent
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '2.18.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5

  firebase_auth: ^3.6.3
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  badges: ^2.0.3
  faker: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  firebase_database: ^9.1.3
  firebase_image: ^1.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.6
  email_validator: ^2.1.17
  string_validator: ^0.3.0
  shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Bold.ttf
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Medium.ttf
        - asset: assets/fonts/Dancing_Script/static/DancingScript-Regular.ttf
        - asset: assets/fonts/Dancing_Script/static/DancingScript-SemiBold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/store/
  
  uses-material-design: true